Section A: Data Structures & Control Structures

In [10]:
# Create list
numbers = [10, 20, 30, 40, 50]
# append
numbers.append(60)
print("After appending:",numbers)
# extend
numbers.extend([70, 80])
print("After extend",numbers)
# insert
numbers.insert(1, 15)
print("After insert:",numbers)
# remove
numbers.remove(30)
print("After removing:",numbers)
# pop
numbers.pop()
print("After poping:",numbers)
# index
print("Index of 40:", numbers.index(40))
# count
print("Count of 20:", numbers.count(20))
# sort
numbers.sort()
print("After sorting:",numbers)
# reverse
numbers.reverse()
print("After reversing:",numbers)
# clear
numbers.clear()
print("After clear:", numbers)

After appending: [10, 20, 30, 40, 50, 60]
After extend [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 15, 20, 30, 40, 50, 60, 70, 80]
After removing: [10, 15, 20, 40, 50, 60, 70, 80]
After poping: [10, 15, 20, 40, 50, 60, 70]
Index of 40: 3
Count of 20: 1
After sorting: [10, 15, 20, 40, 50, 60, 70]
After reversing: [70, 60, 50, 40, 20, 15, 10]
After clear: []


In [14]:
students = ("Navya", "Asha", "Rahul")
students
students[1] = "Megha" 

TypeError: 'tuple' object does not support item assignment

In [15]:
my_set = {1, 2, 2, 3, 4, 4, 5}
print(my_set)

{1, 2, 3, 4, 5}


In [17]:
person = {
    "name": "Navya",
    "age": 22,
    "city": "Bangalore"
}
# Update age
person["age"] = 23

# Add new key
person["email"] = "navy12@email.com"
print(person)

{'name': 'Navya', 'age': 23, 'city': 'Bangalore', 'email': 'navy12@email.com'}


In [28]:
age = 34

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [27]:
marks=80
if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail")

B


In [26]:
num =40
if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Positive but Odd


Section B: Numpy

In [ ]:
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [29]:
import numpy as np
# Scalar
scalar = np.array(5)
# 1D array
arr1 = np.array([1,2,3,4,5])
# 2D array
arr2 = np.arange(10, 70, 10).reshape(2,3)
print(scalar)
print(arr1)
print(arr2)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [30]:
random_array = np.random.randint(0, 100, (4,4))
print(random_array)

[[77 85 37 56]
 [80 23 53 87]
 [85 31 28 71]
 [10 44 73 90]]


In [31]:
import pandas as pd
array_2d = np.random.randint(1, 10, (3,3))
df = pd.DataFrame(array_2d, columns=["A", "B", "C"])
print(df)

   A  B  C
0  3  1  1
1  9  1  5
2  4  3  5


Section C: Exploring Pandas

In [35]:
data = {
    "Name": ["A","B","C","D","E","F","G","H","I","J"],
    "Age": [22,23,24,25,26,27,28,29,30,31],
    "City": ["BLR","DEL","MUM","BLR","DEL","MUM","BLR","DEL","MUM","BLR"],
    "Salary": [50000,60000,None,55000,62000,None,58000,60000,62000,58000]
}

df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,A,22,BLR,50000.0
1,B,23,DEL,60000.0
2,C,24,MUM,NaN
3,D,25,BLR,55000.0
4,E,26,DEL,62000.0
5,F,27,MUM,NaN
6,G,28,BLR,58000.0
7,H,29,DEL,60000.0
8,I,30,MUM,62000.0
9,J,31,BLR,58000.0


In [33]:
### use .info(),.describe()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


,Age,Salary
count,10.00000,8.000000
mean,26.50000,58125.000000
std,3.02765,4015.594601
min,22.00000,50000.000000
25%,24.25000,57250.000000
50%,26.50000,59000.000000
75%,28.75000,60500.000000
max,31.00000,62000.000000


In [36]:
### Select 'Name' and 'City' columns
df[["Name", "City"]]


,Name,City
0,A,BLR
1,B,DEL
2,C,MUM
3,D,BLR
4,E,DEL
5,F,MUM
6,G,BLR
7,H,DEL
8,I,MUM
9,J,BLR


In [37]:
####  Drop 'City' column
df = df.drop("City", axis=1)

In [48]:
#### Fill any missing values in 'Salary' column with the mean
df.fill({"Salary":df["Salary"].mean()},inplace=True)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (394214557.py, line 2)

In [41]:
####  Remove any duplicate rows
df.drop_duplicates(inplace=True)
df

,Name,Age,Salary
0,A,22,50000.0
1,B,23,60000.0
2,C,24,58125.0
3,D,25,55000.0
4,E,26,62000.0
5,F,27,58125.0
6,G,28,58000.0
7,H,29,60000.0
8,I,30,62000.0
9,J,31,58000.0
